const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const inquirer = require('inquirer');

const writeFileAsync = promisify(fs.writeFile);

// Create an array of questions for user input
const questions = [
  {
    type: 'input',
    name: 'title',
    message: "What is your project's title?",
  },
  {
    type: 'input',
    name: 'description',
    message: 'Provide a short description of your project:',
  },
  // Include additional questions as needed
];

// Create a function to write README file
async function writeToFile(fileName, data) {
  try {
    const filePath = path.join(__dirname, fileName);
    await writeFileAsync(filePath, data);
    console.log(`README file generated: ${filePath}`);
  } catch (error) {
    console.error('An error occurred while generating the README file:', error);
  }
}

// Create a function to initialize app
async function init() {
  try {
    console.log('Welcome to the README generator! Please provide the following information:');
    const answers = await inquirer.prompt(questions);
    const readmeContent = generateReadme(answers);
    await writeToFile('README.md', readmeContent);
  } catch (error) {
    console.error('An error occurred during initialization:', error);
  }
}

// Function to generate the README content based on user input
function generateReadme(data) {
  return `# ${data.title}

## Description

${data.description}

## Table of Contents (Optional)

- [Installation](#installation)
- [Usage](#usage)
- [Credits](#credits)
- [License](#license)

## Installation

Describe the steps required to install your project.

## Usage

Provide instructions and examples for use.

## Credits

List your collaborators, if any.

## License

Include the license information for your project.

---
Generated by README at your own risk`;
}

// Function call to initialize app
init();
